version: build.{build}
image: Visual Studio 2017
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: >-
    gitversion /l console /output buildserver /updateAssemblyInfo

    nuget restore
build:
  verbosity: minimal
before_package:
- cmd: clone-extensions.cmd
after_build:
- ps: >-
    $nuget_version = "$env:GitVersion_NuGetVersionV2"

    .\.packages\package-NBi.ps1 $nuget_version
test_script:
- cmd: >-
    nunit3-console NBi.Testing.Core\bin\debug\NBi.Testing.Core.dll NBi.Testing.Framework\bin\debug\NBi.Testing.Framework.dll NBi.Testing.GenbiL\bin\debug\NBi.Testing.GenbiL.dll NBi.Testing.Xml\bin\debug\NBi.Testing.Xml.dll  --where "cat!=Acceptance and cat!=Olap and cat!=Etl and cat!=WindowsService and cat!=ReportServerDB and cat!=LocalSQL" --result=myresults.xml;format=AppVeyor
    
    nunit-console-x86 NBi.Testing\bin\debug\NBi.Testing.dll /exclude:Olap,Etl,WindowsService,ReportServerDB,LocalSQL
    
artifacts:
- path: NBi.NUnit.Runtime\bin\Debug
  name: Framework
- path: NBi.UI.Genbi\bin\Debug
  name: UI
- path: Extensions\genbil
  name: TextMate Bundle
- path: .nupkg\NBi.*.nupkg
  name: Nuget packages
deploy:
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    branch: develop
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  server: https://www.myget.org/F/nbi-framework/api/v2/package
  api_key:
    secure: +E89GuWTCkM1DpiRGoO3oRLIvLIjb8aPsHqNvga0ID/xdUx0cvDjI7XVdF12rmEm
  on:
    branch: /^(develop|feature\/.+|hotfix\/.+)$/
- provider: NuGet
  server: https://nuget.pkg.github.com/Seddryck/index.json
  username: Seddryck
  api_key:
    secure: vmXLz/XAhXz3eNJPtg5mP78yhliNVtPy4ieiwuGD9Ym47b5CvdXLT0B4tr/VHDoX
  on:
    branch: develop
- provider: NuGet
  server: https://nuget.pkg.github.com/Seddryck/index.json
  username: Seddryck
  api_key:
    secure: vmXLz/XAhXz3eNJPtg5mP78yhliNVtPy4ieiwuGD9Ym47b5CvdXLT0B4tr/VHDoX
  on:
    APPVEYOR_REPO_TAG: true